### ISSUE TITLE
Cant seem to unzip the downloaded zip file - corrupt? 

### ISSUE THREAD

**Issue by ghe0106** [twostraws/HackingWithSwift#13]
I have downloaded the zip onto my mac twice now and even attempted to repair it using the zip command - but no luck  .... is anyone else having this issue? Getting Error 2

**Comment by ghe0106** [comment]
btw - just bought ur book

**Comment by twostraws** [comment]
I just downloaded the zip and it works fine for me. The zip isn't actually made by me – it's automatically generated by GitHub based on the current files in the repository.

As you're having trouble, try using `git clone https://github.com/twostraws/HackingWithSwift.git` from the command line. This will download the source files directly from GitHub rather than using the zip.

Please let me know if this doesn't work for you.

**Comment by ghe0106** [comment]
Thanks - just disabled desktop firewall - did the trick !
