### ISSUE TITLE
+ add contact leftBarButtonItem never loads

### ISSUE THREAD

**Issue by BangPotential** [twostraws/HackingWithSwift#26]
The build succeeds, but the bar never loads so I can never add a contact.

The master Project10 obviously works fine. Is there anything else I can check other than the "initial view controller" box being checked.

I was a little confused by my Collection View PersonCell only having the label Person even after I had typed PersonCell and hit enter as prescribed. I have restarted the project once and gone back half way once so any tips would be much appreciated. Apologies if this is the wrong place to add a query.

**Comment by twostraws** [comment]
GitHub isn't a great place for solving problems like this – please email me instead: paul@hackingwithswift.com. You'll need to explain what you mean by "the bar never loads", because it isn't clear right now. I'm guessing you mean you don't see a navigation bar, which suggests you didn't embed your view controller inside a navigation controller.
